language: cpp

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - gcc-8
      - libboost-all-dev
      - libgtest-dev
    env:
      - COMPILER=g++-8
      - CXX=g++-8

dist: xenial

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
