language: cpp

os: linux

addons:
  apt:
    packages:
      - libboost-all-dev

dist: focal

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake -D WITH_TESTS=1 ..

script: make -j$(nproc) && make test
