language: cpp

os: linux

dist: jammy

addons:
  apt:
    packages:
      - cmake
      - make
      - libboost-program-options-dev

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake -D WITH_TESTS=1 ..

script:
  - make -j$(nproc)
  - make test
