language: cpp

dist: xenial

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get -y install libboost-all-dev libgtest-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
