language: cpp

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - gcc-8
      - clang-8
      - libc++-8-dev
      - libc++abi-8-dev
      - libboost-all-dev
      - libgtest-dev

dist: xenial

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
