language: cpp

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libboost-all-dev

dist: xenial

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - export CXX=g++-8
  - cmake ..

script: make && make test
