language: cpp

os: linux

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - g++-9
      - libboost-all-dev

dist: xenial

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - export CXX=g++-9
  - cmake -D WITH_TESTS=1 ..

script: make && make test
